version: '2'

services:

    app:
        image: php
        volumes:
            - ./:/var/www/html

    db:
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: database

        image: mysql
        ports:
            - 3306:3306
        volumes:
            - /var/lib/mysql

    php:
        build: ./docker/php
        links:
            - db
        ports:
            - 80:80
        volumes_from:
            - app
